### ISSUE TITLE
Error after copy a page

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/grid#22] opened 2018-09-04 05:35 UTC
if you copy a complete page tree, the grid elements "Separator" and "End" have the message "Kein Elternelement verbunden".

**Comment by dmolineus** [comment] 2018-09-04 06:16
That's a known limitation when copying grid content elemetns or form elements. You can reassign them using multiple edit tool. Duplicate of #5.

**Closed by dmolineus** 2018-09-04 06:16 UTC
